### ISSUE TITLE
How could I solve "tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU"

### ISSUE THREAD

**Issue by Celeste-cj** [isarandi/metro-pose3d#1]

**Comment by isarandi** [comment]
I'm still investigating the cause of this, perhaps I'll switch to NHWC order.

Either way, the prediction works correctly for me, despite the error message.

**Comment by isarandi** [comment]
Fixed by switching to NHWC order for the exported models (although I think it was a harmless warning/error).
