### ISSUE TITLE
why the keypoint number you claimed in README.md differs from that in inference.py

### ISSUE THREAD

**Issue by Celeste-cj** [isarandi/metro-pose3d#2]
In README.md

> It takes a single RGB image of a person as input and returns the 3D coordinates of **17 body joints** relative to the pelvis. 

In inference.py

`
edges = [(1, 0), (0, 18), (0, 2), (2, 3), (3, 4), (0, 8), (8, 9), (9, 10), (18, 5), (5, 6),
                     (6, 7), (18, 11), (11, 12), (12, 13), (15, 14), (14, 1), (17, 16), (16, 1)]
`

And it seems that the actual predicts have dimensions **more than 19**

**Comment by isarandi** [comment]
You are absolutely right, the docs will be updated.

**Comment by isarandi** [comment]
I updated the docs and scripts to show that these are COCO joints (previously the exported model also contained more joints which correspond to H36M and 3DHP joints, but they are highly redundant with the COCO ones, so for simplicity and clarity I only export COCO joints for the models trained on many datasets.)
